### ISSUE TITLE
Buggy behavior when `jpm_tree` exists

### ISSUE THREAD

**Issue by CFiggers** [CFiggers/janet-lsp#10]
Currently two (at least) issues are appearing when there is a `jpm_tree` containing local files:

1) Some on-hover documentation points toward the `jpm_tree`, especially module imports (even when the module is not being imported from `jpm_tree`)
2) When `(import)`ing, any symbol inserted will be accepted as valid, even when that module does not exist; any modules contained in `jpm_tree` will then be suggested by autocompletion namespaced under that symbol
   - (This seems to be happening on *each keystroke*, meaning that if `(import random)` is typed, `r`, `ra`, `ran`, `rand`, etc. are all evaluated)

Probably has something to do with the way modules are being identified in `jpm_tree`---more experimentation needed.

**Comment by sogaiu** [comment]
Some more data about a possibly related case follows.

Preparation steps:

```
# time of writing 80ef23e0
git clone https://github.com/CFiggers/janet-lsp
cd janet-lsp
jpm -l deps
```

Using [vscode-janet-plus-plus](https://github.com/CFiggers/vscode-janet-plus-plus) v1.1.2, take a look at any of the following files from the cloned `janet-lsp` project:

* `doc.janet`
* `eval.janet`
* `lookup.janet`
* `misc.janet`

Here, for each file, the last instance of `deftest` is underlined in red.

There is an associated message:

```
unknown symbol deftest
```

For reference, I currently have "Don't Discover Jpm Tree" unchecked for vscode-janet-plus-plus.

---

OS: Void Linux
VSCode: 1.85.1 (vscode-1.85.1 from void-packages)

**Comment by CFiggers** [comment]
Improvements to jpm_tree detection in v0.0.13— @sogaiu if you want to kick the tires and let me know if it works as expected now, I'd love to close this issue complete!

**Comment by sogaiu** [comment]
I don't have access to a similar environment, but I tried with:

* Xubuntu 26.04 - live image -- not an installation
* VSCodium 1.126.04524 - installed via [`.deb` at gh repository](https://github.com/VSCodium/vscodium/releases/tag/1.126.04524)
* vscode-janet-plus-plus 1.1.11 (f1d2ca3) - installed via cli install of [downloaded `.vsix`](https://github.com/CFiggers/vscode-janet-plus-plus/releases/tag/v1.1.11)
* janet-lsp (53caed6c) - cloned to view files
* jpm (0827f643) - installed from cloned source (`PREFIX=$HOME/.local`)
* janet (4370ae8a) - built and installed from cloned source (`PREFIX=$HOME/.local`)

[`deftest` only seems to exist in `misc.janet` now](https://github.com/CFiggers/janet-lsp/blob/53caed6cde401c62f26a8e895c5e6316614aa0ae/src/misc.janet#L6) but the one that's there wasn't underlined in red.

That seems good, but I noticed that vscode-janet-plus-plus seemed to be having difficulties starting (or connecting to?) `janet-lsp` (presumably the one that is bundled with the extension).

May be there's some pilot error here setting things up and such...sorry, it's been a while since I've used VSCod* 😅 

In any case, I turned debugging on via the extension settings, restarted, and observed the following output.

<details>
<pre>
[Error - 11:49:17 PM] Client Janet Language Server: connection to server is erroring.
write EPIPE
Shutting down server.
[Error - 11:49:17 PM] Client Janet Language Server: connection to server is erroring.
write EPIPE
[Error - 11:49:17 PM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: starting
	at b.shutdown (/home/xubuntu/.vscode-oss/extensions/calebfiggers.vscode-janet-plus-plus-1.1.11/dist/extension.js:2:2122292)
	at b.stop (/home/xubuntu/.vscode-oss/extensions/calebfiggers.vscode-janet-plus-plus-1.1.11/dist/extension.js:2:2121873)
	at b.stop (/home/xubuntu/.vscode-oss/extensions/calebfiggers.vscode-janet-plus-plus-1.1.11/dist/extension.js:2:2184)
	at b.handleConnectionError (/home/xubuntu/.vscode-oss/extensions/calebfiggers.vscode-janet-plus-plus-1.1.11/dist/extension.js:2:2128352)
	at process.processTicksAndRejections (node:internal/process/task_queues:104:5)
[Error - 11:49:17 PM] Server initialization failed.
  Message: write EPIPE
  Code: -32099 
[Error - 11:49:17 PM] Janet Language Server client: couldn't create connection to server.
  Message: write EPIPE
  Code: -32099 
[Info  - 11:49:17 PM] Connection to server got closed. Server will restart.
true
error: expected iterable type, got nil
  in drop [boot.janet] on line 1295, column 29
  in args [/home/deck/.local/share/janet/lib/cmd/arg-parser.janet] on line 146, column 31
  in main [src/main.janet] (tail call) on line 527, column 20
  in run-main [boot.janet] on line 4691, column 16
  in cli-main [boot.janet] on line 4904, column 13
[Error - 11:49:17 PM] Server process exited with code 1.
error: expected iterable type, got nil
  in drop [boot.janet] on line 1295, column 29
  in args [/home/deck/.local/share/janet/lib/cmd/arg-parser.janet] on line 146, column 31
  in main [src/main.janet] (tail call) on line 527, column 20
  in run-main [boot.janet] on line 4691, column 16
  in cli-main [boot.janet] on line 4904, column 13
[Error - 11:49:17 PM] Server process exited with code 1.
[Error - 11:49:17 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 11:49:17 PM] Connection to server got closed. Server will restart.
true
[Error - 11:49:17 PM] Janet Language Server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
error: expected iterable type, got nil
  in drop [boot.janet] on line 1295, column 29
  in args [/home/deck/.local/share/janet/lib/cmd/arg-parser.janet] on line 146, column 31
  in main [src/main.janet] (tail call) on line 527, column 20
  in run-main [boot.janet] on line 4691, column 16
  in cli-main [boot.janet] on line 4904, column 13
[Error - 11:49:17 PM] Server process exited with code 1.
[Error - 11:49:17 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 11:49:17 PM] Connection to server got closed. Server will restart.
true
[Error - 11:49:17 PM] Janet Language Server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 11:49:17 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
error: expected iterable type, got nil
  in drop [boot.janet] on line 1295, column 29
  in args [/home/deck/.local/share/janet/lib/cmd/arg-parser.janet] on line 146, column 31
  in main [src/main.janet] (tail call) on line 527, column 20
  in run-main [boot.janet] on line 4691, column 16
  in cli-main [boot.janet] on line 4904, column 13
[Error - 11:49:17 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 11:49:17 PM] Connection to server got closed. Server will restart.
true
[Error - 11:49:17 PM] Janet Language Server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 11:49:17 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 11:49:17 PM] Server process exited with code 1.
error: expected iterable type, got nil
  in drop [boot.janet] on line 1295, column 29
  in args [/home/deck/.local/share/janet/lib/cmd/arg-parser.janet] on line 146, column 31
  in main [src/main.janet] (tail call) on line 527, column 20
  in run-main [boot.janet] on line 4691, column 16
  in cli-main [boot.janet] on line 4904, column 13
[Error - 11:49:17 PM] Server process exited with code 1.
[Error - 11:49:17 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 11:49:17 PM] The Janet Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 11:49:17 PM] Janet Language Server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 11:49:17 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
</pre>
</details>

**Comment by CFiggers** [comment]
Hmm. Something has gone wrong there for sure.

This is the section of code in `cmd` that's throwing the error:

https://github.com/CFiggers/cmd/blob/b0a34d6e854578bd672d43303e80b9777af08b42/src/arg-parser.janet#L145-L147

IIUC, the `*args*` dynamic variable _should_ always have at least one value in it, namely, the name of the executing program. For it to be `nil`... something isn't working correctly.

**Comment by sogaiu** [comment]
From the output above is it possible to tell if `janet-lsp` was started?

**Comment by CFiggers** [comment]
From the output above it's possible to be quite confident that it did not start. :) It never got past parsing command line arguments and crashed, five times in rapid succession.

**Comment by sogaiu** [comment]
Thanks.

I tried installing a locally built `janet-lsp` and configured the extension to use it [1].

After I restarted VSCodium, I did not observe any of the error output from before [2].

So it seems to be working better now :)

Viewing `misc.janet` and looking at `deftest`, I see no red underline, nor do I see the `unknown symbol deftest` message.

---

[1] I entered `janet-lsp` in one of the extension's text fields and I verified that the `janet-lsp` on my `PATH` was the one I installed.

[2] I see a bunch of linting messages now instead :)

<details>
<pre>
Starting LSP 0.0.13-53caed6
/home/xubuntu/.local/lib/janet/judge/util.janet:90:1: compile warning (normal): binding catseq is shadowing a macro
/home/xubuntu/.local/lib/janet/cmd/util.janet:58:1: compile warning (normal): binding assertf is shadowing a macro
/home/xubuntu/.local/lib/janet/cmd/bridge.janet:72:7: compile warning (normal): binding doc is shadowing a macro
/home/xubuntu/.local/lib/janet/cmd/param-parser.janet:123:1: compile warning (normal): binding default is shadowing a macro
/home/xubuntu/.local/lib/janet/cmd/param-parser.janet:135:1: compile warning (normal): binding default is shadowing a macro
/home/xubuntu/.local/lib/janet/cmd/init.janet:79:1: compile warning (normal): binding spec is shadowing a macro
/home/xubuntu/.local/lib/janet/cmd/init.janet:133:1: compile warning (normal): binding defn is shadowing a macro
/home/xubuntu/.local/lib/janet/cmd/init.janet:136:1: compile warning (normal): binding spec is shadowing a macro
libs/jpm-defs.janet:97:1: compile warning (normal): binding rule is shadowing a macro
libs/jpm-defs.janet:101:1: compile warning (normal): binding task is shadowing a macro
libs/jpm-defs.janet:106:1: compile warning (normal): binding phony is shadowing a macro
libs/jpm-defs.janet:110:1: compile warning (normal): binding sh-rule is shadowing a macro
libs/jpm-defs.janet:114:1: compile warning (normal): binding sh-task is shadowing a macro
libs/jpm-defs.janet:118:1: compile warning (normal): binding sh-phony is shadowing a macro
libs/jpm-defs.janet:122:1: compile warning (normal): binding phony is shadowing a macro
libs/jpm-defs.janet:126:1: compile warning (normal): binding add-body is shadowing a macro
../../.local/lib/janet/judge/util.janet:90:1: compile warning (normal): binding catseq is shadowing a macro
</pre>
</details>

**Comment by sogaiu** [comment]
I made another attempt in a different environment.

This time I used Linux Mint 22.3 via qemu and also via booting an installation `.iso`.

All other bits were the same:

* VSCodium 1.126.04524 - installed via [.deb at gh repository](https://github.com/VSCodium/vscodium/releases/tag/1.126.04524)
* vscode-janet-plus-plus 1.1.11 (f1d2ca3) - installed via cli install of [downloaded .vsix](https://github.com/CFiggers/vscode-janet-plus-plus/releases/tag/v1.1.11)
* janet-lsp (https://github.com/CFiggers/janet-lsp/commit/53caed6cde401c62f26a8e895c5e6316614aa0ae) - cloned to view files
* jpm (0827f643) - installed from cloned source (PREFIX=$HOME/.local)
* janet (4370ae8a) - built and installed from cloned source (PREFIX=$HOME/.local)

I got the same results as [previously mentioned](https://github.com/CFiggers/janet-lsp/issues/10#issuecomment-5234506266), i.e. the bundled `janet-lsp` does not appear to start.

The error output looks similar to me:

<details>
<pre>
[Error - 5:50:48 AM] Client Janet Language Server: connection to server is erroring.
write EPIPE
Shutting down server.
[Error - 5:50:48 AM] Client Janet Language Server: connection to server is erroring.
write EPIPE
[Error - 5:50:48 AM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: starting
	at b.shutdown (/home/mint/.vscode-oss/extensions/calebfiggers.vscode-janet-plus-plus-1.1.11/dist/extension.js:2:2122292)
	at b.stop (/home/mint/.vscode-oss/extensions/calebfiggers.vscode-janet-plus-plus-1.1.11/dist/extension.js:2:2121873)
	at b.stop (/home/mint/.vscode-oss/extensions/calebfiggers.vscode-janet-plus-plus-1.1.11/dist/extension.js:2:2184)
	at b.handleConnectionError (/home/mint/.vscode-oss/extensions/calebfiggers.vscode-janet-plus-plus-1.1.11/dist/extension.js:2:2128352)
	at process.processTicksAndRejections (node:internal/process/task_queues:104:5)
[Error - 5:50:48 AM] Server initialization failed.
  Message: write EPIPE
  Code: -32099 
[Error - 5:50:48 AM] Janet Language Server client: couldn't create connection to server.
  Message: write EPIPE
  Code: -32099 
[Info  - 5:50:48 AM] Connection to server got closed. Server will restart.
true
error: expected iterable type, got nil
  in drop [boot.janet] on line 1295, column 29
  in args [/home/deck/.local/share/janet/lib/cmd/arg-parser.janet] on line 146, column 31
  in main [src/main.janet] (tail call) on line 527, column 20
  in run-main [boot.janet] on line 4691, column 16
  in cli-main [boot.janet] on line 4904, column 13
[Error - 5:50:48 AM] Server process exited with code 1.
error: expected iterable type, got nil
  in drop [boot.janet] on line 1295, column 29
  in args [/home/deck/.local/share/janet/lib/cmd/arg-parser.janet] on line 146, column 31
  in main [src/main.janet] (tail call) on line 527, column 20
  in run-main [boot.janet] on line 4691, column 16
  in cli-main [boot.janet] on line 4904, column 13
[Error - 5:50:48 AM] Server process exited with code 1.
[Error - 5:50:48 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 5:50:48 AM] Connection to server got closed. Server will restart.
true
[Error - 5:50:48 AM] Janet Language Server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
error: expected iterable type, got nil
  in drop [boot.janet] on line 1295, column 29
  in args [/home/deck/.local/share/janet/lib/cmd/arg-parser.janet] on line 146, column 31
  in main [src/main.janet] (tail call) on line 527, column 20
  in run-main [boot.janet] on line 4691, column 16
  in cli-main [boot.janet] on line 4904, column 13
[Error - 5:50:48 AM] Server process exited with code 1.
[Error - 5:50:48 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 5:50:48 AM] Connection to server got closed. Server will restart.
true
[Error - 5:50:48 AM] Janet Language Server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 5:50:48 AM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
error: expected iterable type, got nil
  in drop [boot.janet] on line 1295, column 29
  in args [/home/deck/.local/share/janet/lib/cmd/arg-parser.janet] on line 146, column 31
  in main [src/main.janet] (tail call) on line 527, column 20
  in run-main [boot.janet] on line 4691, column 16
  in cli-main [boot.janet] on line 4904, column 13
[Error - 5:50:48 AM] Server process exited with code 1.
[Error - 5:50:48 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 5:50:48 AM] Connection to server got closed. Server will restart.
true
[Error - 5:50:48 AM] Janet Language Server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 5:50:48 AM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
error: expected iterable type, got nil
  in drop [boot.janet] on line 1295, column 29
  in args [/home/deck/.local/share/janet/lib/cmd/arg-parser.janet] on line 146, column 31
  in main [src/main.janet] (tail call) on line 527, column 20
  in run-main [boot.janet] on line 4691, column 16
  in cli-main [boot.janet] on line 4904, column 13
[Error - 5:50:48 AM] Server process exited with code 1.
[Error - 5:50:48 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 5:50:48 AM] The Janet Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 5:50:48 AM] Janet Language Server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 5:50:48 AM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
</pre>
</details>

**Comment by sogaiu** [comment]
Ok, I've now also tried lower versions of vscode-janet-plus-plus, specifically, 1.1.6, 1.1.8, and 1.1.10.  This didn't significantly change any results.

I downgraded janet though (from latest master to 1.41.2) and this seems to have done the trick.

---

So may be there is a separate issue and it should be either over at the vscode-janet-plus-plus or janet repositories.

Some speculation...may be the `.jimage` is not compatible...

**Comment by sogaiu** [comment]
Looks like the `.jimage` compatibility may have been the issue.

I copied a new `janet-lsp.jimage` [1] over the extension's `janet-lsp.jimage` and a subsequent restart of VSCodium exhibited no errors and vscode-janet-plus-plus seemed to be happy [2].

---

Is there an "official story" around which versions of `janet` are supposed to work?  I took a quick look at vscode-janet-plus-plus's `README` and didn't notice anything.

Sorry, I guess some of this content ought to live at the vscode-janet-plus-plus repository 😅 

---

[1] ...from the `build` directory within a cloned `janet-lsp` repository where a build had been done using the latest master branch `janet`.

[2] I did make sure to blank the text field in the extension's settings for specifying a custom `janet-lsp` command.
